### ISSUE TITLE
minimatch.defaults crashes with TypeError in 3.0.4

### ISSUE THREAD

**Issue by sandersn** [isaacs/minimatch#139]
`minimatch.defaults` isn't callable like minimatch itself is:

```
> var m = require('minimatch')
> m('hi', 'hi')
true
> m.defaults({ example: true })('hi', 'hi')
Uncaught TypeError: orig.minimatch is not a function
    at minimatch (/home/nathansa/src/test/node_modules/minimatch/minimatch.js:77:17)
```

Found by checking minimatch with Typescript.

**Comment by isaacs** [comment]
Seems to work in 3.0.5.
